development:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: matrimonial
  username: root
  password: root

test:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: matrimonial
  username: root
  password: root

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: matrimonial
  username: root
  password: root
